Fix react script error
creativetimofficial/argon-dashboard-react pull request #24
Opened 2020-03-03 14:06 UTC by QuentinGruber

Fix #23 :smile:

2020-03-03 14:06 UTC, QuentinGruber commented
@timcreative

2020-03-04 08:13 UTC, einazare requested changes
- [x] PR should point to customer-support branch
- [x] We only allow exact versions inside our package.json dependencies, i.e., `"react-scripts": "^3.4.0",` should be `"react-scripts": "3.4.0",`

2020-03-05 08:13 UTC, einazare approved these changes

2020-03-05 08:14 UTC, einazare approved these changes

2020-03-05 08:15 UTC, merged